--- # Configuration settings for VICGL Model
VICGL_1_0.0: # Configuration settings for static glaciers
  MODEL: Variable Infiltration Capacity Model
  VERSION: 1.0
  DESCRIPTION: Standard run without glacier dynamics
  COMPILE_OPTIONS:
    Simulation_Parameters:
      NO_REWIND: FALSE
      LINK_DEBUG: TRUE
      CLOSE_ENERGY: FALSE
      LOW_RES_MOIST: FALSE
      QUICK_FS: FALSE
      SPATIAL_FROST: FALSE
      SPATIAL_SNOW: FALSE
      EXCESS_ICE: FALSE
    Maximum_Array_Sizes:
      MAX_BANDS: 20
      MAX_FRONTS: 3
      MAX_LAKE_NODES: 20
      MAX_LAYERS: 3
      MAX_NODES: 50
    Snow_Constants:
      TraceSnow: 0.030000
    Other_Constants:
      LAI_WATER_FACTOR: 0.200000
      LWAVE_COR: 1.000000
      MAXIT_FE: 25
  RUN_TIME_OPTIONS:
    Simulation_Dimensions:
      NLAYER: 3
      EQUAL_AREA: FALSE
      RESOLUTION: 0.062500
      TIME_STEP: 3
      SNOW_STEP: 3
    Simulation_Parameters:
      AERO_RESIST_CANSNOW: AR_406_FULL
      BLOWING: FALSE
      COMPUTE_TREELINE: FALSE
      CONTINUEONERROR: FALSE
      CORRPREC: FALSE
      DIST_PRCP: FALSE
      EXP_TRANS: FALSE
      FROZEN_SOIL: FALSE
      FULL_ENERGY: TRUE
      GRND_FLUX_TYPE: GF_410
      IMPLICIT: FALSE
      LW_TYPE: LW_TVA
      LW_CLOUD: LW_CLOUD_DEARDORFF
      MIN_WIND_SPEED: 0.100000
      MTCLIM_SWE_CORR: TRUE
      NODES: 3
      NOFLUX: FALSE
      PLAPSE: TRUE
      PREC_EXPT: 0.600000
      QUICK_FLUX: TRUE
      QUICK_SOLVE: FALSE
      SNOW_ALBEDO: USACE
      SNOW_DENSITY: DENS_BRAS
      SW_PREC_THRESH: 0.000000
      TEMP_TH_TYPE: KIENZLE
      TFALLBACK: TRUE
      VP_INTERP: TRUE
      VP_ITER: VP_ITER_ALWAYS
    Forcing:
      GRID_DECIMAL: 5
      WIND_H: 10.000000
      MEASURE_H: 2.000000
      ALMA_INPUT: FALSE
      N_TYPES: 8
      FORCE_TYPE: PREC
      FORCE_TYPE: AIR_TEMP
      FORCE_TYPE: SHORTWAVE
      FORCE_TYPE: LONGWAVE
      FORCE_TYPE: DENSITY
      FORCE_TYPE: PRESSURE
      FORCE_TYPE: VP 
      FORCE_TYPE: WIND
      FORCE_DT: 3
    Soil:
      BASEFLOW: ARNO
      JULY_TAVG_SUPPLIED: TRUE
      ORGANIC_FRACT: FALSE
    Vegetation:
      ROOT_ZONES: 3
      VEGPARAM_LAI: FALSE
      LAI_SRC: LAI_FROM_VEGLIB
    Elevation:
      BAND_SIZE: 200
      BAND_TYPE: FIXED
      SNOW_BAND: 20
    Glacier_Dynamics:
      GLACIER_DYNAMICS: FALSE
      GLACIER_ACCUM_START_MONTH: NA
      GLACIER_ACCUM_START_DAY: NA
      GLACIER_ACCUM_INTERVAL: NA
    Lake:
      LAKES: FALSE
      LAKE_PROFILE: FALSE
    Output_Data:
      OUT_STEP: 24
      MOISTFRACT: FALSE

VICGL_1_0.1: # Configuration settings for dynamic glaciers
  MODEL: Variable Infiltration Capacity Model
  VERSION: 1.0
  DESCRIPTION: Standard run with glacier dynamics
  COMPILE_OPTIONS:
    Simulation_Parameters:
      NO_REWIND: FALSE
      LINK_DEBUG: TRUE
      CLOSE_ENERGY: FALSE
      LOW_RES_MOIST: FALSE
      QUICK_FS: FALSE
      SPATIAL_FROST: FALSE
      SPATIAL_SNOW: FALSE
      EXCESS_ICE: FALSE
    Maximum_Array_Sizes:
      MAX_BANDS: 20
      MAX_FRONTS: 3
      MAX_LAKE_NODES: 20
      MAX_LAYERS: 3
      MAX_NODES: 50
    Snow_Constants:
      TraceSnow: 0.030000
    Other_Constants:
      LAI_WATER_FACTOR: 0.200000
      LWAVE_COR: 1.000000
      MAXIT_FE: 25
  RUN_TIME_OPTIONS:
    Simulation_Dimensions:
      NLAYER: 3
      EQUAL_AREA: FALSE
      RESOLUTION: 0.062500
      TIME_STEP: 3
      SNOW_STEP: 3
    Simulation_Parameters:
      AERO_RESIST_CANSNOW: AR_406_FULL
      BLOWING: FALSE
      COMPUTE_TREELINE: FALSE
      CONTINUEONERROR: FALSE
      CORRPREC: FALSE
      DIST_PRCP: FALSE
      EXP_TRANS: FALSE
      FROZEN_SOIL: FALSE
      FULL_ENERGY: TRUE
      GRND_FLUX_TYPE: GF_410
      IMPLICIT: FALSE
      LW_TYPE: LW_TVA
      LW_CLOUD: LW_CLOUD_DEARDORFF
      MIN_WIND_SPEED: 0.100000
      MTCLIM_SWE_CORR: TRUE
      NODES: 3
      NOFLUX: FALSE
      PLAPSE: TRUE
      PREC_EXPT: 0.600000
      QUICK_FLUX: TRUE
      QUICK_SOLVE: FALSE
      SNOW_ALBEDO: USACE
      SNOW_DENSITY: DENS_BRAS
      SW_PREC_THRESH: 0.000000
      TEMP_TH_TYPE: KIENZLE
      TFALLBACK: TRUE
      VP_INTERP: TRUE
      VP_ITER: VP_ITER_ALWAYS
    Forcing:
      GRID_DECIMAL: 5
      WIND_H: 10.000000
      MEASURE_H: 2.000000
      ALMA_INPUT: FALSE
      N_TYPES: 8
      FORCE_TYPE: PREC
      FORCE_TYPE: AIR_TEMP
      FORCE_TYPE: SHORTWAVE
      FORCE_TYPE: LONGWAVE
      FORCE_TYPE: DENSITY
      FORCE_TYPE: PRESSURE
      FORCE_TYPE: VP 
      FORCE_TYPE: WIND
      FORCE_DT: 3
    Soil:
      BASEFLOW: ARNO
      JULY_TAVG_SUPPLIED: TRUE
      ORGANIC_FRACT: FALSE
    Vegetation:
      ROOT_ZONES: 3
      VEGPARAM_LAI: FALSE
      LAI_SRC: LAI_FROM_VEGLIB
    Elevation:
      BAND_SIZE: 200
      BAND_TYPE: FIXED
      SNOW_BAND: 20
    Glacier_Dynamics:
      GLACIER_DYNAMICS: TRUE
      GLACIER_ACCUM_START_MONTH: 10
      GLACIER_ACCUM_START_DAY: 1
      GLACIER_ACCUM_INTERVAL: 1
    Lake:
      LAKES: FALSE
      LAKE_PROFILE: FALSE
    Output_Data:
      OUT_STEP: 24
      MOISTFRACT: FALSE
